### ISSUE TITLE
Doesn't load in Tampermonkey (Chrome)

### ISSUE THREAD

**Issue by Aerozol** [afrocatmusic/userscripts#2]
The script doesn't load for me in Tampermonkey, on Chrome.

It works after changing:

```
// @match       *://musicbrainz.*/release*
// @match       *://beta.musicbrainz.*/release*
```

to:

```
// @match       *://musicbrainz.org/release*
// @match       *://beta.musicbrainz.org/release*
```

Seems like an easy fix, but I'll let you decide how you want to handle it or maybe you can find a better fix (presumably you wanted to include the .eu domain)

**Comment by afrocatmusic** [comment]
yeah i want to include all the variations, beta, eu, http (does anyone still use http?)
try this instead
`// @match       *://*.musicbrainz.*/release/*`
works for me even though i would expect it not to because of the . before "musicbrainz"

**Comment by Aerozol** [comment]
Hmm, doesn't work for me.

This works though, so it seems to be that third asterisk that's causing trouble:

`// @match       *://*.musicbrainz.org/release/*`

Tried a few different variations but couldn't get it to work without explicitly writing '.org'

**Comment by afrocatmusic** [comment]
I can mark this as solved, right? do the new match rules work fine for you?

**Comment by Aerozol** [comment]
Yeah, thanks!

**Comment by jesus2099** [comment]
Instead of wordy:

https://github.com/afrocatmusic/userscripts/blob/6c607f6b67136d0446552a6058a630f15481020d/afros-sublinks.user.js#L6-L8

You can use, either:

```js
// @match       *://*.musicbrainz.org/*
// @match       *://musicbrainz.eu/*
```

Or:

```js
// @include     /^https?:\/\/((beta|test)\.)?musicbrainz.(org|eu)\//
```

**Comment by jesus2099** [comment]
I do like regex includes, too.
But I’ve read somewhere that there might be problems with them in that Manifest v3 thing.
